// This file is automatically generated. Do not modify it manually.
import type { FirebaseOptions } from 'firebase/app';

export const firebaseConfig: FirebaseOptions = {
  apiKey: "YOUR_API_KEY",
  authDomain: "beautifulsoupandfood-198cd.firebaseapp.com",
  projectId: "beautifulsoupandfood-198cd",
  storageBucket: "beautifulsoupandfood-198cd.appspot.com",
  messagingSenderId: "YOUR_MESSAGING_SENDER_ID",
  appId: "YOUR_APP_ID",
};
